# netlify.toml
[[redirects]]
  force = true
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/directory/game/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/:name/videos/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/settings"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "_site"

[dev]
  autoLaunch = false
  command = "npx @11ty/eleventy --port 8080 --serve"
  targetPort = 8080

